### ISSUE TITLE
Add support for the "simplePaginate" method

### ISSUE THREAD

**Issue by philippe-tellier** [andreyvolosyuk/simple-eloquent#1]
It would be useful to also have support for the [simplePaginate](https://laravel.com/api/5.5/Illuminate/Database/Eloquent/Builder.html#method_simplePaginate) method.

I might submit a PR in the next few weeks.

Great job with this plugin BTW, much needed and appreciated!

**Comment by andreyvolosyuk** [comment]
@philippe-tellier, done) 
Thanks for review!

**Comment by philippe-tellier** [comment]
@andreyvolosyuk Awesome, thanks a lot!
