### ISSUE TITLE
Simple query to keep same API

### ISSUE THREAD

**Issue by antonkomarev** [andreyvolosyuk/simple-eloquent#2]
Just an idea, maybe it will be good to have `simpleQuery` method for the Eloquent models which will switch behavior to simple methods, but will keep an old methods naming.

```php
$users = User::simpleQuery()->where('is_active', true)->get();
```

**Comment by andreyvolosyuk** [comment]
@a-komarev your idea looks beautiful :)
Does it have another benefits?
I guess it can cause issue regarding backward compatibility.
And can you tell me what is the reason of higher attention to this package?) Today I got more stars then 5 months before :)

**Comment by antonkomarev** [comment]
Don't know about increasing attention, I found it accidentally. I was looked completely another thing on GitHub, clicked on your profile somewhere and dived in repositories.
I don't have plans to use this package right now, just dropped my 2 cents because it looks interesting.

I can see only one benefit of the example I've provided - similar APIs easier to maintain.
Possibly developer could change `simpleQuery` to `query` on the fly if there is requirement to have more functionality in some cases, but it's controversial statement. Because if there will be usage of methods which aren't supported in `SimpleEloquent` this feature will be useless.

**Comment by antonkomarev** [comment]
Ideally it would be great to use `simpleQuery` until not supported method will be called and then switch to default `query`. But I'm pretty sure it would be impossible or near to impossible and increase overhead.

**Comment by andreyvolosyuk** [comment]
I agree that your suggestion is more pretty than mine. But how often do you see usage like `User::query()->where()`? In this case `query` can be omitted and developers like to do that.

In general I just extended `Eloquent/Builer` and added some new methods. Hence `SimpleEloquent/Builder` will have the same functionality as `Eloquent/Builder` plus some new methods which work with query execution.

I guess it's not possible to change api now because some people use this extension already. At least I can just create aliases for `*Simple()` methods to adhere to default api.

**Comment by antonkomarev** [comment]
You are right, I didn't see `query()` a lot in the wild. But personally I'm using it pretty frequently when need to add conditions depends of the request.

```php
$query = User::query();

if ($something) {
    $query->where('something', 'value');
}

if ($somethingElse) {
    $query->where('somethingElse', 'value');
}

$users = $query->get();
```

**Comment by andreyvolosyuk** [comment]
@a-komarev if you need I can add some aliases and that static method for you :)

**Comment by antonkomarev** [comment]
Do not think that I impose my decision on you, just thinking about all possible ways of clean API which could be easier for developers to start implementing in already exists applications.

Another one thing I'm thinking about:
```php
$users = User::where('is_active', true)->simple()->get();
```

**Comment by andreyvolosyuk** [comment]
No, I'm opened for new ideas which can improve this package. And I find your ideas useful and appropriate.

**Comment by antonkomarev** [comment]
I understood what I don't like in your API. Inconsistency.
Compare this methods: `allSimple` & `findSimpleOrFail`.
I understand that your logic was adding word simple after first word, but in my point of view it should be added at the end everywhere: `allSimple` & `findOrFailSimple()`, or even better at the beginning `simpleAll()` & `simpleFindOrFail`.
And method names `simplePaginateSimple` and `paginateSimple` looks pretty ambiguous. But if `simple` keyword will be before the method name it will be much worse: `simpleSimplePaginate` & `simplePaginate` (this method will have name conflict).

**Comment by andreyvolosyuk** [comment]
You're right. I didn't pay enough attention for name convention. Just focused on functionality.

**Comment by antonkomarev** [comment]
Anyway, easiest and cleanest solution I've wrote couple of comments below, magic method `simple` which will encapsulate your custom methods calls:
```php
$users = User::simple()->paginate();
$users = User::where('something', 'value')->simple()->simplePaginate();
```

If this is possible to implement then API will be same as default Eloquent. It will have a big impact on the ease of entry for the new developers.

**Comment by andreyvolosyuk** [comment]
@a-komarev, so how would you interpret User::where('is_active', 1)->simple()->sum()?
simple() method can be usable but in such situation is totally redudant?

**Comment by antonkomarev** [comment]
If there is no `sum` method in your SimpleEloquent Builder, you could pass it to default Eloquent Builder.

**Comment by andreyvolosyuk** [comment]
@a-komarev could you check it out and share your opinion?
