### ISSUE TITLE
Hidden Fields

### ISSUE THREAD

**Issue by sineld** [andreyvolosyuk/simple-eloquent#4]
`User::simple()->paginate(5);`

Reveals hidden attributes like **password** and **remember_token**.

This should be fixed.

**Comment by andreyvolosyuk** [comment]
Yes, I know about such vulnerability. The main aim was to make it fast. I even mentioned this
> Since you'll get stdClasses|arrays you won't reach out to casting, appends, guarded/fillable, crud and another possibilities. That's why new methods are much faster

I can go through all of the columns and remove hidden attributes. But such action will add overhead and make everything slower.

So I decided to make you responsible for it :)

I would recommend you such solution. It can solve your problem.
https://laracasts.com/series/incremental-api-development/episodes/4

**Comment by sineld** [comment]
Yes @andreyvolosyuk I have missed that line.
Thanks for quick reply.

**Comment by andreyvolosyuk** [comment]
@sineld check my response out please, i updated it
