### ISSUE TITLE
Problem with ide-helper

### ISSUE THREAD

**Issue by MIcQo** [andreyvolosyuk/simple-eloquent#5]
Hello, i have confict or something like that with this package and `barryvdh/laravel-ide-helper`  

```
PHP Fatal error:  Illuminate\Database\Eloquent\Relations\Relation and Volosyuk\SimpleEloquent\Relations\Relation define the same property ($morphMap) in the composition of Volosyuk\S
impleEloquent\Relations\BelongsTo. However, the definition differs and is considered incompatible. Class was composed in vendor\volosyuk\simple-e
In BelongsTo.php line 12:

  Illuminate\Database\Eloquent\Relations\Relation and Volosyuk\SimpleEloquent\Relations\Relation define the same property ($morphMap) in the composition of Volosyuk\SimpleEloquent
  \Relations\BelongsTo. However, the definition differs and is considered incompatible. Class was composed
```

i just add trait into model and then ran `artisan ide-helper:model -W`

**Comment by andreyvolosyuk** [comment]
Hi! What laravel version  do you use?

**Comment by MIcQo** [comment]
i use latest version installed with composer

**Comment by andreyvolosyuk** [comment]
what does 'composer show | grep laravel' tell?

**Comment by MIcQo** [comment]
`There are no commands defined in the "composer" namespace. ` without `grep`
something like this. Can we solve this problem ?

**Comment by andreyvolosyuk** [comment]
Ok, I guess I know the sense of problem.
I updated some peace of code. Can you update a package and run ide-helper?

> composer update volosyuk/simple-eloquent

**Comment by MIcQo** [comment]
Yeah! it works.
Thank you for solve this problem.

**Comment by andreyvolosyuk** [comment]
You're welcom :)
